#!/usr/bin/env node
/**
 * Build the browser bundle (lib/client.js) from the canonical client source
 * (src/client/index.js).
 *
 * The web module loader expects a factory-form bundle:
 *
 *   window.__ModuleLoader__.load({
 *     id: "<package name>",
 *     factory: (require) => { ...; return module.exports; }
 *   });
 *
 * The source is a small, controlled ESM module, so the transform is a fixed
 * set of literal edits (each asserted before replacement); any drift in the
 * source fails the build loudly instead of emitting a broken bundle.
 *
 * The generated lib/client.js is committed to the repository and shipped in
 * the npm tarball (files: "lib"), so profile installs — npm or GitHub — get a
 * ready bundle with no build step and no prepare script.
 *
 * Usage: node scripts/build-client.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const sourcePath = join(root, 'src', 'client', 'index.js');
const outPath = join(root, 'lib', 'client.js');

const source = readFileSync(sourcePath, 'utf8');

/** Apply one literal transform, failing when the expected text is absent. */
function transform(text, pattern, replacement, what) {
  if (!pattern.test(text)) throw new Error(`build-client: expected ${what} in ${sourcePath}`);
  return text.replace(pattern, replacement);
}

let body = source;
body = transform(body, /import \* as React from 'react';\n/, 'let React = require("react");\n', 'the React import');
body = transform(body, /export const name = /, 'const name = ', 'the name export');
body = transform(body, /export const inject = /, 'const inject = ', 'the inject export');
body = transform(body, /export function apply\(/, 'function apply(', 'the apply export');
if (/\nexport /.test(body)) throw new Error('build-client: leftover top-level ESM export in transformed source');

const bundle = [
  '/* generated by scripts/build-client.mjs from src/client/index.js — do not edit by hand */',
  'window.__ModuleLoader__.load({',
  `\tid: ${JSON.stringify(pkg.name)},`,
  '\tfactory: (require) => {',
  '\t\tvar module = { exports: {} };',
  '\t\tvar exports = module.exports;',
  '\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });',
  '',
  '\t\t' + body.trim().replace(/\n/g, '\n\t\t'),
  '',
  '\t\texports.name = name;',
  '\t\texports.inject = inject;',
  '\t\texports.apply = apply;',
  '\t\treturn module.exports;',
  '\t}',
  '});',
  ''
].join('\n');

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, bundle);
console.log(`build-client: ${outPath} (${bundle.length} bytes) for ${pkg.name}@${pkg.version}`);
